### ISSUE TITLE
Very Slow Training with low GPU Usage - Tensorflow Version?

### ISSUE THREAD

**Issue by deeplearningfam** [thunguyenphuoc/HoloGAN#12]
Hi,

great work! I was wondering if someone knows why training is so slow and the GPU usage is very low (~ 600MB in my case)? I got it working with tensorflow 1.15, not sure if an even older version works better - it does not work with a newer version.

Thanks a lot for your help!

**Comment by ebartrum** [comment]
Did you manage to improve this with an older version?

> Hi,
> 
> great work! I was wondering if someone knows why training is so slow and the GPU usage is very low (~ 600MB in my case)? I got it working with tensorflow 1.15, not sure if an even older version works better - it does not work with a newer version.
> 
> Thanks a lot for your help!
